export const inputFormElements = [
  {
    name: "first_name",
    placeholder: "Enter first name",
    label: "First Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "last_name",
    placeholder: "Enter last name",
    label: "Last Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "user_name",
    placeholder: "Enter complete name",
    label: "User Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "email",
    type: "email",
    placeholder: "Enter email",
    label: "Email",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "password",
    type: "password",
    placeholder: "Password",
    label: "Password",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "phone",
    type: "number",
    placeholder: "Enter phone number",
    label: "Phone",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "company",
    placeholder: "Enter company name",
    label: "Company Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "companyAddress",
    placeholder: "Enter company address",
    label: "Company address",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "companyWebsite",
    placeholder: "Enter company website",
    label: "Company Website",
    variant: "outlined",
    fullWidth: true,
    required: false,
    xs: 12,
    sm: 12,
  },
  {
    name: "street",
    placeholder: "Enter street",
    label: "Street",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "city",
    placeholder: "Enter city name",
    label: "City",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "state",
    placeholder: "Enter state",
    label: "State",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "country",
    placeholder: "Enter country name",
    label: "Country",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "pincode",
    placeholder: "Enter pincode number",
    label: "Pincode",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "title",
    placeholder: "Enter project Title",
    label: "Project Title",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "name",
    placeholder: "Enter project short name",
    label: "Project Short Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "description",
    placeholder: "Enter Project Description",
    label: "Descritpion",
    variant: "outlined",
    fullWidth: true,
    required: true,
    multiline: true,
    rows: 5,
    xs: 12,
    sm: 12,
  },
  // {
  //   name: "type",
  //   placeholder: "Enter project Type",
  //   label: "Project Type",
  //   variant: "outlined",
  //   fullWidth: true,
  //   required: true,
  //   xs: 12,
  //   sm: 12,
  // },
  {
    name: "portfolio",
    placeholder: "Enter project portfolio",
    label: "Project Protfoilio",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "budget",
    placeholder: "Enter project budget",
    label: "Project Budget",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "fund_source",
    placeholder: "Enter fund source",
    label: "Fund Source",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
  {
    name: "budget",
    placeholder: "Enter project budget",
    label: "Project Budget",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 12,
  },
];
